In [18]:
import sqlite3
import pandas as pd

In [19]:
conn = sqlite3.connect("mykpopidolsdatabase.db")
cursor = conn.cursor()

In [20]:
cursor.execute("DROP TABLE IF EXISTS kpopagency")
cursor.execute("DROP TABLE IF EXISTS kpopidolgroup")
cursor.execute("DROP TABLE IF EXISTS kpopgroupmembers")
conn.commit()

In [21]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS kpopagency(id
    INTEGER PRIMARY KEY AUTOINCREMENT,
    agency TEXT,
    location TEXT,
    date_established DATE,
    number_of_kpop_groups_debuted INT,
    ownername TEXT
)
""")
conn.commit()

In [22]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS kpopidolgroup(id
    INTEGER PRIMARY KEY AUTOINCREMENT,
    kpop_group_name TEXT,
    type TEXT,
    debut_date DATE,
    number_of_members INT,
    agencyID INT
)
""")
conn.commit()

In [23]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS kpopgroupmembers(idol_member_id
    INTEGER PRIMARY KEY AUTOINCREMENT,
    stage_name TEXT,
    real_name TEXT,
    gender TEXT,
    birthday DATE,
    position TEXT,
    zodiac TEXT,
    personality_type TEXT,
    kpopgroup_id INTEGER,
    agency_id INTEGER
)
""")
conn.commit()

In [24]:
agencies_data = [
    ("SM Entertainment", "Seoul, South Korea", "1995-02-14", 15, "Lee Soo-man"),
    ("YG Entertainment", "Seoul, South Korea", "1996-02-24", 10, "Yang Hyun-suk"),
    ("JYP Entertainment", "Seoul, South Korea", "1997-04-25", 10, "Park Jin-young"),
    ("HYBE Entertainment", "Seoul, South Korea", "2005-02-01", 8, "Bang Si-hyuk"),
    ("Starship Entertainment", "Seoul, South Korea", "2008-01-28", 6, "Kim Shi-dae"),
    ("Cube Entertainment", "Seoul, South Korea", "2006-08-29", 7, "Hong Seung-sung"),
    ("Pledis Entertainment", "Seoul, South Korea", "2007-01-01", 5, "Han Sung-soo"),
    ("RBW", "Seoul, South Korea", "2010-03-05", 4, "Kim Jin-woo"),
    ("Woollim Entertainment", "Seoul, South Korea", "2003-09-01", 6, "Lee Jung-yeop"),
    ("FNC Entertainment", "Seoul, South Korea", "2006-12-14", 8, "Han Seong-ho")
]

cursor.executemany("""
    INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername) 
    VALUES(?, ?, ?, ?, ?)
""", agencies_data)
conn.commit()

In [25]:
df_agencies = pd.read_sql_query("SELECT * FROM kpopagency", conn)
df_agencies

,id,agency,location,date_established,number_of_kpop_groups_debuted,ownername
0,1,SM Entertainment,"Seoul, South Korea",1995-02-14,15,Lee Soo-man
1,2,YG Entertainment,"Seoul, South Korea",1996-02-24,10,Yang Hyun-suk
2,3,JYP Entertainment,"Seoul, South Korea",1997-04-25,10,Park Jin-young
3,4,HYBE Entertainment,"Seoul, South Korea",2005-02-01,8,Bang Si-hyuk
4,5,Starship Entertainment,"Seoul, South Korea",2008-01-28,6,Kim Shi-dae
5,6,Cube Entertainment,"Seoul, South Korea",2006-08-29,7,Hong Seung-sung
6,7,Pledis Entertainment,"Seoul, South Korea",2007-01-01,5,Han Sung-soo
7,8,RBW,"Seoul, South Korea",2010-03-05,4,Kim Jin-woo
8,9,Woollim Entertainment,"Seoul, South Korea",2003-09-01,6,Lee Jung-yeop
9,10,FNC Entertainment,"Seoul, South Korea",2006-12-14,8,Han Seong-ho

In [26]:
groups_data = [
    ("Red Velvet", "Dual concept girl group", "2014-08-01", 5, 1), 
    ("aespa", "Girl Group", "2020-11-17", 4, 1), 
    ("BLACKPINK", "Girl Group", "2016-08-08", 4, 2), 
    ("TREASURE", "Boy Group", "2020-08-07", 10, 2), 
    ("TWICE", "Girl Group", "2015-10-20", 9, 3), 
    ("Stray Kids", "Boy Group", "2018-03-25", 8, 3), 
    ("BTS", "Boy Group", "2013-06-13", 7, 4), 
    ("TXT", "Boy Group", "2019-03-04", 5, 4), 
    ("LE SSERAFIM", "Girl Group", "2022-05-02", 5, 4), # Changed from IVE, updated agency to HYBE
    ("CORTIS", "Boy Group", "2015-05-14", 6, 5) # Changed from MONSTA X
]

cursor.executemany("""
    INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID) 
    VALUES(?, ?, ?, ?, ?)
""", groups_data)
conn.commit()

In [27]:
df_groups = pd.read_sql_query("SELECT * FROM kpopidolgroup", conn)
df_groups

,id,kpop_group_name,type,debut_date,number_of_members,agencyID
0,1,Red Velvet,Dual concept girl group,2014-08-01,5,1
1,2,aespa,Girl Group,2020-11-17,4,1
2,3,BLACKPINK,Girl Group,2016-08-08,4,2
3,4,TREASURE,Boy Group,2020-08-07,10,2
4,5,TWICE,Girl Group,2015-10-20,9,3
5,6,Stray Kids,Boy Group,2018-03-25,8,3
6,7,BTS,Boy Group,2013-06-13,7,4
7,8,TXT,Boy Group,2019-03-04,5,4
8,9,LE SSERAFIM,Girl Group,2022-05-02,5,4
9,10,CORTIS,Boy Group,2015-05-14,6,5

In [28]:
members_data = [
    ("Irene", "Bae Joo-hyun", "Female", "1991-03-29", "Leader", "Aries", "INFJ", 1, 1),
    ("Karina", "Yoo Ji-min", "Female", "2000-04-11", "Leader", "Aries", "ENFP", 2, 1),
    ("Jisoo", "Kim Ji-soo", "Female", "1995-01-03", "Visual", "Capricorn", "INFJ", 3, 2),
    ("Haruto", "Watanabe Haruto", "Male", "2004-04-05", "Rapper", "Aries", "ISFP", 4, 2),
    ("Nayeon", "Im Na-yeon", "Female", "1995-09-22", "Lead Vocalist", "Virgo", "ISTP", 5, 3),
    ("Bang Chan", "Christopher Bahng", "Male", "1997-10-03", "Leader", "Libra", "ENFJ", 6, 3),
    ("RM", "Kim Nam-joon", "Male", "1994-09-12", "Leader", "Virgo", "ENFP", 7, 4),
    ("Yeonjun", "Choi Yeon-jun", "Male", "1999-09-13", "Dancer", "Virgo", "ENFP", 8, 4),
    ("Chaewon", "Kim Chae-won", "Female", "2000-08-01", "Leader", "Leo", "ISTP", 9, 4), # Replaced Wonyoung with Chaewon
    ("Shownu", "Sohn Hyun-woo", "Male", "1992-06-18", "Leader", "Gemini", "ISFJ", 10, 5) # Shownu is now linked to CORTIS
]

cursor.executemany("""
    INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id) 
    VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)
""", members_data)
conn.commit()

In [29]:
df_members = pd.read_sql_query("SELECT * FROM kpopgroupmembers", conn)
df_members

,idol_member_id,stage_name,real_name,gender,birthday,position,zodiac,personality_type,kpopgroup_id,agency_id
0,1,Irene,Bae Joo-hyun,Female,1991-03-29,Leader,Aries,INFJ,1,1
1,2,Karina,Yoo Ji-min,Female,2000-04-11,Leader,Aries,ENFP,2,1
2,3,Jisoo,Kim Ji-soo,Female,1995-01-03,Visual,Capricorn,INFJ,3,2
3,4,Haruto,Watanabe Haruto,Male,2004-04-05,Rapper,Aries,ISFP,4,2
4,5,Nayeon,Im Na-yeon,Female,1995-09-22,Lead Vocalist,Virgo,ISTP,5,3
5,6,Bang Chan,Christopher Bahng,Male,1997-10-03,Leader,Libra,ENFJ,6,3
6,7,RM,Kim Nam-joon,Male,1994-09-12,Leader,Virgo,ENFP,7,4
7,8,Yeonjun,Choi Yeon-jun,Male,1999-09-13,Dancer,Virgo,ENFP,8,4
8,9,Chaewon,Kim Chae-won,Female,2000-08-01,Leader,Leo,ISTP,9,4
9,10,Shownu,Sohn Hyun-woo,Male,1992-06-18,Leader,Gemini,ISFJ,10,5

In [14]:
conn.close()